spring:
  application:
    name: eureka

server:
  port: 8761

eureka:
  instance:
    hostname: ${SERVER_IP:127.0.0.1}
    prefer-ip-address: true  
    leaseRenewalIntervalInSeconds: 3
    leaseExpirationDurationInSeconds: 3   
  client:
    registerWithEureka: false
    fetchRegistry: false
  server:
    waitTimeInMsWhenSyncEmpty: 5
  serviceUrl:
    defaultZone: ${EUREKA:http://eureka:8761/eureka}